version: '1.0'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
      - ./.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    depends_on:
      - postgres

volumes:
  postgres-db: